### PR TITLE
Added Windows Hello Integration and Local Passcode feature to Unigram

### PR DESCRIPTION
**Pull request by prajjwaldimri**
Concerns #220

### CODE REVIEW

**Comment by brullsker** [comment]
@prajjwaldimri Good idea

**Comment by prajjwaldimri** [comment]
@FrayxRulez Any updates on this one?

**Comment by larsschellhas** [comment]
Actually we have some issues still.

1. I would say it is not secure, if the Chat list loads right behind your dialog-box, asking for the Password
2. Why isn´t it possible to use Windows Hello and a Passcode/PIN side-by-side?

**Comment by prajjwaldimri** [comment]
The verification operation is actually asynchronous so it lets the thread that launches the  app running. It is more balanced in terms of usability and security IMO as it provides seamless experience. As far as security is concerned you just cannot skip, cancel or close that dialog as canceling it will trigger the application.exit method in unigram.

You cannot use the local passcode and windows hello at the same time because Windows hello itself provides a passcode option and it would seem redundant to enter the passcode two times.

Sent from my Windows 10 phone

**Comment by larsschellhas** [comment]
As far as I see it, someone could get Information about your Chats, even if he doesn´t have your Login-data.
And even if this Information is Little, because you only see the chatlist in the Background, it is still there and that shouldn´t be! I understand that, you want to start up the app in the Background for better UX, but IMHO at least it shouldn´t be possible to see anything before entering the correct passphrase.

Second: What if someone wants to use both Options side-by-side, I mean either Login via biometrics or another Password/PIN than the one, which is set in Windows Hello?
What if someone simply wants douple-protection?

**Comment by prajjwaldimri** [comment]
For the privacy thing, I think we could add some blur effect on the chats till the user is authenticated which will result in better UX or just make the verification dialogs full-screen. Both of these options will not result in any delay to app start-up. Other option would be to halt the app start-up till the user verifies his/her identity which will increase the startup time (a little but the user would be able to notice it). 

Also, I advised against the local passcode thing from the very start. IMO we should only use Windows Hello as it is completely sufficient for any type of app. @FrayxRulez wanted to keep the app similar to the original telegram app so I added it. The problem with local passcode is that it is insecure. It is just a string stored in LocalSettings of the app. Whenever a user enters the pin, the app just trims and compares both strings. It cannot fundamentally provide double protection. I can add encryption and decryption algorithms(e.g. bcrypt) for the authentication but that would again cost time which can be significantly higher on lower-end phones. Its just a performance overhead.

Quoting MS on Windows Hello:

>Windows Hello is not just a replacement for traditional 2FA systems, though. It is conceptually similar to smart cards: authentication is performed by using cryptographic primitives instead of string comparisons, and the user’s key material is secure inside tamper-resistant hardware. 

Side-note: If any hacker can bypass Windows Hello which Microsoft recommends to sensitive websites like banking websites etc, then I don't think a locally stored string can hold him/her.

**Comment by larsschellhas** [comment]
Sorry for the late answer.
I am seriously not convinced of your idea to just let the app start up in Background. Since Unigram establishes an encrypted Connection to the Telegram Servers to get all your Messages, it would be ridiculous to let this Connection be established before the authorization is given. 
Also every user who wants his data to be secured should be willing to give the app a few milliseconds more to start up. 

Let´s go on. If someone don´t want to use Windows Hello or even can´t use Windows Hello on his/her device, it wouldn´t be possible to get the app secured at all.
Furthermore a local passcode isn´t insecure. It´s just insecure in the way implemented by you. OF COURSE you never should save a passcode in plane in the app Settings. OF COURSE you Need to work with encription and/or hash-comparism.
And if you say, encryption would take to much ressources, especially on low-budget phones, i suggest to think twice. Unigram encrypts every single message it sends and decrypts every single message it receives. The complete communication is encrypted. That´s probably the key Point of Unigram/Telegram.

Side-note: I should have the possibility to get the app secured, even if I don´t use Windows Hello.

Best Regards and good night! :)

**Comment by ikarago** [comment]
A Passcode option to Unigram (or any chat app, really) is more an option to keep your chats away from accidental prying eyes on your account and NOT an alternative to keep your data completely secure from other people using you account.

Why not? Other people that would be interested in your data (and that are willing to circumvent this to get it) shouldn't be using the pc/phone/Xbox on YOUR account in the first place.

Such a feature thus is only meant to be an extra hurdle to keep others out of your Telegram account (maybe on things like Xbox) from accidental viewing.


This might be a thing we could look into in the future; in how and what such a feature would mean to the user and what should change when such a function is in user, aside from providing that hurdle. ;)

**Comment by prajjwaldimri** [comment]
Alright so I will move the windows hello and pin authentication method call above the initialization call so that nothing else gets executed without the authentication.Also for the pin code problem I will experiment with the bcrypt encryption algorithm and see if I can keep the decryption below 1-3 seconds in lower end devices. Also maybe provide an option to user to use bcrypt encryption or not. How does this sound?

**Comment by larsschellhas** [comment]
@prajjwaldimri @frayxrulez ?

**Comment by FrayxRulez** [comment]
You should take a look to Windows.Security namespace.m

**Comment by rabiet** [comment]
Is still anything happening here?

**Pull request closed without merging**
