### PR TITLE
Shortcuts.md fixes and improvements

### PR DESCRIPTION
**Pull request by makisukurisu**
Archive, removed unnecessary enters (at the end), added clarity for some elements, added Ctrl+W shortcut

If this is too much for such a little update, you may close this PR, and just Ctrl+C, Ctrl+V text from file in makisukuris/Unigram Shortcuts.md

### CODE REVIEW

**Review by MarcAnt01 — APPROVED** [review]
All looking good to me

**Review by seannleckie — COMMENTED** [review]
As this has been approved for months, can it please be accepted into the upstream?

**Comment by MarcAnt01** [comment]
@FrayxRulez 's fault

**Comment by makisukurisu** [comment]
@MarcAnt01 Now it should not. It requires updating (at least) Ctrl+k, also I'd recommend to wait till Ctrl+shift+U or whatever is changed to create links. Rest should be fine, but I'd double check it once again. Is it possible to update PR?

**Comment by MarcAnt01** [comment]
Sure, just make change to makisukurisu:develop and new commits wil appear in the pr

**Comment by FrayxRulez** [comment]
Changes are obsolete

**Comment by MarcAnt01** [comment]
@makisukurisu do you plan to update this pull request or can we close it?

**Comment by makisukurisu** [comment]
I'll recheck it today.

**Comment by makisukurisu** [comment]
Should be it.

**Pull request merged**
