### PR TITLE
Fixed the use of a word in the German locale

### PR DESCRIPTION
**Pull request by strollingHeifer**
While "Thema" exists as a word in German, it is not the translation of the English "Theme".

### CODE REVIEW

**Comment by FrayxRulez** [comment]
Sorry to tell you after all this work, but that’s an auto generated file. 
You might want to suggest the changes to the Android app here: translations.telegram.org

**Comment by strollingHeifer** [comment]
Oh, thank you for pointing that out! I will close the PR.

**Comment by pokurt** [comment]
@FrayxRulez lmaoo

**Comment by pokurt** [comment]
@pokurt okay .. ill suggest. thanks for looking out

**Pull request closed without merging**
