### PR TITLE
Added a few more Emojis for auto-replacement

### PR DESCRIPTION
**Pull request by strollingHeifer**
A few more ways to write out Emojis. These are common across different apps and platforms and therefore should also be auto-completed by Unigram.

### CODE REVIEW

**Review by FrayxRulez — APPROVED** [review]
As you're there... Could you replace ":o" with ":O"? It's kind of annoying while using autocomplete. 
Thanks!

**Comment by strollingHeifer** [comment]
Gotcha. I thought about using ":O" for 😲 instead of 😮. But I don't think that's really common. So I now set both options (":o" and ":O") to use 😮. I think that's the best solution for now, as I've seen both variants across the web.

**Comment by FrayxRulez** [comment]
I would remove ":o" entirely because it prevents from getting further emoji suggestions (such as :ok)

**Comment by strollingHeifer** [comment]
Good point. I wasn't thinking about that.

**Review by FrayxRulez — APPROVED** [review]

**Pull request merged**
